### ISSUE TITLE
Deployment Docs

### ISSUE THREAD

**Issue by rpsimao** [Guja1501/lockscreen#1]
Can you please, put into the Readme file, the Deploymemt docs (examples)?
Thanks

**Comment by Guja1501** [comment]
[Example](https://github.com/Guja1501/lockscreen/blob/ea482e620e4bf0a1e7863cbebf3f086559580587/README.md#examples) for [v1.0.1](https://github.com/Guja1501/lockscreen/releases/tag/v1.0.1)

Thanks for helping to improve the project
